# Generated by Django 5.1.2 on 2024-11-30 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_preferences_plan'),
        ('workout_plan', '0003_remove_trainingday_name_trainingday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_plan.trainingplan'),
        ),
    ]
