# Generated by Django 5.1.2 on 2024-12-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='exercise_videos/'),
        ),
    ]
