# Generated by Django 5.1.2 on 2024-12-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercise_video_url_exercise_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='training_days/'),
        ),
    ]
