# Generated by Django 5.1.2 on 2024-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_description_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
