# Generated by Django 5.1.2 on 2024-12-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_remove_exercise_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description_set',
        ),
    ]
