# Generated by Django 5.1.2 on 2024-12-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_alter_exercise_options_exercise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description_set',
            field=models.TextField(blank=True, null=True),
        ),
    ]
