# Generated by Django 5.1.2 on 2024-12-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useful_materials',
            name='app_link_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
