# Generated by Django 5.1.2 on 2024-11-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainigPlan',
            new_name='TrainingPlan',
        ),
    ]
