# Generated by Django 5.1.2 on 2024-11-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0002_rename_trainigplan_trainingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingday',
            name='name',
        ),
        migrations.AddField(
            model_name='trainingday',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuestday', 'Tuestday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
