# Generated by Django 5.1.2 on 2024-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0003_remove_trainingday_name_trainingday_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingday',
            old_name='exircices',
            new_name='exercises',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='experience',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('fan', 'Fan'), ('pro', 'Pro')], default='medium', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='medium', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=30),
        ),
    ]
