# Generated by Django 5.1.2 on 2024-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0004_rename_exircices_trainingday_exercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=30),
        ),
    ]
