# Generated by Django 5.1.2 on 2024-12-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0005_alter_trainingplan_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingday',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='training_days/'),
        ),
    ]
