# Generated by Django 5.1.2 on 2024-12-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0006_trainingday_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingday',
            name='photo',
        ),
    ]
