# Generated by Django 5.1.2 on 2024-12-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workout_plan', '0007_remove_trainingday_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingday',
            name='exercises',
        ),
        migrations.AddField(
            model_name='trainingday',
            name='exercises',
            field=models.ManyToManyField(related_name='training_days', to='exercises.exercise'),
        ),
    ]
