# Generated by Django 5.1.2 on 2024-11-20 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('gender', models.CharField(choices=[('male', 'Man'), ('female', 'Woman')], max_length=14)),
                ('goal', models.CharField(choices=[('gain weight', 'Gain weight'), ('lose weight', 'Lose weight'), ('recomposition', 'Recomposition')], max_length=14)),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
