# Generated by Django 5.1.2 on 2024-11-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_calculate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcalculation',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (light exercise/sports 1-3 days/week)'), ('moderate', 'Moderately active (moderate exercise/sports 3-5 days/week)'), ('active', 'Very active (hard exercise/sports 6-7 days/week)'), ('very_active', 'Super active (very hard exercise/sports & physical job)')], default=10, max_length=20),
            preserve_default=False,
        ),
    ]
