name: Upload Database to Render

on:
  push:
    branches:
      - main  # или ваша ветка, например master

jobs:
  upload-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload SQLite Database to Render
        run: |
          scp -o StrictHostKeyChecking=no path/to/your/db.sqlite3 username@host:/path/to/render/project/db.sqlite3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Добавьте свой ключ SSH в Secrets
